language: haskell

before_script:
  - cp mongo-dummy.json mongo.json
  - cp tests/mongo-dummy.json tests/mongo.json

script:
  - ~/.cabal/bin/cabal-dev configure --enable-tests
  - ~/.cabal/bin/cabal-dev build
  - ~/.cabal/bin/cabal-dev test

install:
  - sudo apt-get install -qq mongodb-10gen
  - cabal install cabal-dev
  - ~/.cabal/bin/cabal-dev install --only-dependencies --enable-tests